name: Deploy to Cloudflare Pages

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy-to-cloudflare:
    name: Deploy to Cloudflare Pages
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: whilefoo/.github/.github/workflows/deploy.yml@reusable-workflow
    permissions:
      contents: read
      pull-requests: write
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
